"""make_document_id_nullable

Revision ID: b53ed7843d4c
Revises: '0005_conversations'
Create Date: 2026-07-28 19:16:07.172757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53ed7843d4c'
down_revision: Union[str, None] = '0005_conversations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_messages_conv_created', 'conversation_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_conversations_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_conversations_user_updated', table_name='conversations')
    op.drop_index('idx_messages_conv_created', table_name='conversation_messages')
    # ### end Alembic commands ###
